# Generated by Django 5.2.7 on 2025-10-12 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyStudent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('class_section', models.TextField(blank=True, db_column='Class_section', null=True)),
                ('roll_no', models.IntegerField(blank=True, db_column='Roll_no', null=True)),
                ('aadhaar_no', models.IntegerField(blank=True, db_column='Aadhaar_No', null=True)),
                ('father_or_guardian_name', models.TextField(blank=True, db_column='Father_or_guardian_name', null=True)),
                ('mother_name', models.TextField(blank=True, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('name_teacher', models.TextField(blank=True, db_column='Name_teacher', null=True)),
                ('school_name', models.TextField(blank=True, null=True)),
                ('last_school_name', models.TextField(blank=True, null=True)),
                ('place_of_birth', models.TextField(blank=True, null=True)),
                ('known_earlier_disease', models.TextField(blank=True, null=True)),
                ('screen_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('class_section', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('father_or_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('known_earlier_disease', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('muac', models.FloatField(blank=True, null=True)),
                ('muac_sam', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_both', models.CharField(blank=True, max_length=50, null=True)),
                ('vison_left', models.IntegerField(blank=True, null=True)),
                ('vison_right', models.IntegerField(blank=True, null=True)),
                ('vision_problem', models.TextField(blank=True, null=True)),
                ('age_in_month', models.IntegerField(blank=True, null=True)),
                ('deworming', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination', models.CharField(blank=True, max_length=255, null=True)),
                ('covid', models.CharField(blank=True, max_length=50, null=True)),
                ('tea_garden', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('age_screening', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.student')),
            ],
            options={
                'ordering': ['-screen_date'],
            },
        ),
    ]
