# Generated by Django 5.2.7 on 2026-03-13 10:23

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_date', models.DateField(blank=True, null=True)),
                ('class_section', models.CharField(blank=True, max_length=50, null=True)),
                ('screening_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('academic_year', models.CharField(blank=True, choices=core.models.academic_year_choices, db_index=True, max_length=9, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('muac', models.FloatField(blank=True, null=True)),
                ('muac_sam', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_age', models.TextField(blank=True, null=True)),
                ('length_age', models.TextField(blank=True, null=True)),
                ('weight_height', models.TextField(blank=True, null=True)),
                ('vision_both', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_left', models.CharField(blank=True, max_length=10, null=True)),
                ('vision_right', models.CharField(blank=True, max_length=10, null=True)),
                ('vision_problem', models.TextField(blank=True, null=True)),
                ('age_in_month', models.IntegerField(blank=True, null=True)),
                ('covid', models.CharField(blank=True, max_length=50, null=True)),
                ('age_screening', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-screen_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deworming', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination', models.CharField(blank=True, max_length=255, null=True)),
                ('B1_severe_anemia', models.BooleanField(default=False)),
                ('B2_vitA_deficiency', models.BooleanField(default=False)),
                ('B3_vitD_deficiency', models.BooleanField(default=False)),
                ('B4_goitre', models.BooleanField(default=False)),
                ('B5_oedema', models.BooleanField(default=False)),
                ('C1_convulsive_dis', models.BooleanField(default=False)),
                ('C2_otitis_media', models.BooleanField(default=False)),
                ('C3_dental_condition', models.BooleanField(default=False)),
                ('C4_skin_condition', models.BooleanField(default=False)),
                ('C5_rheumatic_heart_disease', models.BooleanField(default=False)),
                ('C6_others_TB_asthma', models.BooleanField(default=False)),
                ('D1_difficulty_seeing', models.BooleanField(default=False)),
                ('D2_delay_in_walking', models.BooleanField(default=False)),
                ('D3_stiffness_floppiness', models.BooleanField(default=False)),
                ('D5_reading_writing_calculatory_difficulty', models.BooleanField(default=False)),
                ('D6_speaking_difficulty', models.BooleanField(default=False)),
                ('D7_hearing_problems', models.BooleanField(default=False)),
                ('D8_learning_difficulties', models.BooleanField(default=False)),
                ('D9_attention_difficulties', models.BooleanField(default=False)),
                ('E3_depression_sleep', models.BooleanField(default=False)),
                ('E4_menarke', models.BooleanField(default=False)),
                ('E5_regularity_period_difficulties', models.BooleanField(default=False)),
                ('E6_UTI_STI', models.BooleanField(default=False)),
                ('E7_discharge', models.BooleanField(default=False)),
                ('E8_menstrual_pain', models.BooleanField(default=False)),
                ('E9_remarks', models.TextField(blank=True, null=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.screening')),
            ],
            options={
                'verbose_name': 'Screening Check',
                'verbose_name_plural': 'Screening Checks',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('father_or_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('known_earlier_disease', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.student'),
        ),
    ]
