# Generated by Django 5.2.7 on 2026-02-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyStudent',
        ),
    ]
