# Generated by Django 5.2.7 on 2026-03-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='screening_year',
        ),
    ]
