# Generated by Django 5.2.7 on 2026-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_screening_screening_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='screening_type',
            field=models.CharField(choices=[('full', 'Full Screening'), ('partial', 'Partial Screening')], default='full', max_length=10),
        ),
    ]
