# Generated by Django 5.2.7 on 2026-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_screening_screening_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
    ]
