# Generated by Django 5.2.7 on 2025-10-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_current_class_section_student_current_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_school',
            new_name='school',
        ),
    ]
