# Generated by Django 5.2.7 on 2026-03-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_screening_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
    ]
