# Generated by Django 5.2.7 on 2026-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_screening_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcheck',
            name='show_in_stats',
            field=models.BooleanField(default=False),
        ),
    ]
