# Generated by Django 5.2.7 on 2026-03-13 09:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_screening_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='academic_year',
            field=models.CharField(choices=core.models.academic_year_choices, db_index=True, max_length=9),
        ),
    ]
