# Generated by Django 5.2.7 on 2025-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='length_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='weight_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='weight_height',
            field=models.TextField(blank=True, null=True),
        ),
    ]
