# Generated by Django 5.2.7 on 2025-10-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_screening_length_age_screening_weight_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1_severe_anemia', models.BooleanField(default=False)),
                ('B2_vitA_deficiency', models.BooleanField(default=False)),
                ('B3_vitD_deficiency', models.BooleanField(default=False)),
                ('B4_goitre', models.BooleanField(default=False)),
                ('B5_oedema', models.BooleanField(default=False)),
                ('C1_convulsive_dis', models.BooleanField(default=False)),
                ('C2_otitis_media', models.BooleanField(default=False)),
                ('C3_dental_condition', models.BooleanField(default=False)),
                ('C4_skin_condition', models.BooleanField(default=False)),
                ('C5_rheumatic_heart_disease', models.BooleanField(default=False)),
                ('C6_others_TB_asthma', models.BooleanField(default=False)),
                ('D1_difficulty_seeing', models.BooleanField(default=False)),
                ('D2_delay_in_walking', models.BooleanField(default=False)),
                ('D3_stiffness_floppiness', models.BooleanField(default=False)),
                ('D5_reading_writing_calculatory_difficulty', models.BooleanField(default=False)),
                ('D6_speaking_difficulty', models.BooleanField(default=False)),
                ('D7_hearing_problems', models.BooleanField(default=False)),
                ('D8_learning_difficulties', models.BooleanField(default=False)),
                ('D9_attention_difficulties', models.BooleanField(default=False)),
                ('E3_depression_sleep', models.BooleanField(default=False)),
                ('E4_menarke', models.BooleanField(default=False)),
                ('E5_regularity_period_difficulties', models.BooleanField(default=False)),
                ('E6_UTI_STI', models.BooleanField(default=False)),
                ('E7_discharge', models.BooleanField(default=False)),
                ('E8_menstrual_pain', models.BooleanField(default=False)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.screening')),
            ],
            options={
                'verbose_name': 'Screening Check',
                'verbose_name_plural': 'Screening Checks',
            },
        ),
    ]
