# Generated by Django 5.2.7 on 2025-10-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_screeningcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='deworming',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='screeningcheck',
            name='deworming',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='screeningcheck',
            name='vaccination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
