# Generated by Django 5.2.7 on 2025-10-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_screening_deworming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcheck',
            name='E9_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
