# Generated by Django 5.2.7 on 2025-10-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_screeningcheck_e9_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='status',
        ),
    ]
