# Generated by Django 5.2.7 on 2025-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_screening_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='tea_garden',
        ),
        migrations.AddField(
            model_name='student',
            name='tea_garden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
