# Generated by Django 5.2.7 on 2025-10-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_screening_tea_garden_student_tea_garden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='vison_left',
            new_name='vision_left',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='vison_right',
            new_name='vision_right',
        ),
    ]
