# Generated by Django 5.2.7 on 2025-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_vison_left_screening_vision_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='vision_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='vision_right',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
