# Generated by Django 5.2.7 on 2025-11-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_screening_vision_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='aadhaar_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_school_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tea_garden',
        ),
    ]
