# Generated by Django 5.2.7 on 2025-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_student_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='place_of_birth',
        ),
    ]
